version: '3.8'

services:
  gameapi:
    build:
      context: ./GameAPI
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    networks:
      - my_network
    environment:
      - MONGO_URI=mongodb://root:password@mongodb:27017/gamedetails?authSource=admin
    depends_on:
      - mongodb
  
  userapi:
    build:
      context: ./UserAPI
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    networks:
      - my_network
    environment:
      - MONGO_URI=mongodb://root:password@mongodb:27017/userdetails?authSource=admin
    depends_on:
      - mongodb

  mongodb:
    image: mongo:4.4
    ports:
      - "27017:27017"
    networks:
      - my_network
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password

networks:
  my_network:
    driver: bridge

