apiVersion: apps/v1
kind: Deployment
metadata:
  name: userapi
  namespace: my-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: userapi
  template:
    metadata:
      labels:
        app: userapi
    spec:
      containers:
      - name: userapi
        image: docker.io/library/userapi:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5001
        env:
        - name: MONGO_URI
          value: "mongodb://root:password@mongodb.my-app.svc.cluster.local:27017/userdetails?authSource=admin"
---
apiVersion: v1
kind: Service
metadata:
  name: userapi
  namespace: my-app
spec:
  type: NodePort
  selector:
    app: userapi
  ports:
    - protocol: TCP
      port: 5001
      targetPort: 5001
      nodePort: 30334
