apiVersion: v1
kind: PersistentVolume
metadata:
  name: db
  labels:
    type: local
spec:
  storageClassName: {{ .Values.persistentVolume.storageClassName }}
  capacity:
    storage: {{ .Values.persistentVolume.size }}
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/data/db"
