apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db
  namespace: {{ .Values.namespace }}
spec:
  storageClassName: {{ .Values.persistentVolume.storageClassName }}
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.persistentVolume.size }}
